version: "3.9"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django_api
    restart: unless-stopped
    volumes:
        - ./dot:/app
    ports:
      - 8000:8000